SPOOL database.log
DECLARE
	PROCEDURE drop_user_if_exists 
	AS
		not_needed NUMBER;
	BEGIN
		EXECUTE IMMEDIATE 'DROP USER &1 CASCADE';
	EXCEPTION 
		WHEN OTHERS 
		THEN NULL;
	END drop_user_if_exists;
	
BEGIN
	drop_user_if_exists();
	
	EXECUTE IMMEDIATE 'CREATE USER &1 IDENTIFIED BY nhibernate
		DEFAULT TABLESPACE KRT
		TEMPORARY TABLESPACE TEMP
		QUOTA UNLIMITED ON KRT 
		QUOTA UNLIMITED ON KRI';

	EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CONNECT, RESOURCE, CREATE PROCEDURE, CREATE TRIGGER TO &1';

	EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_LOCK TO &1';
END;
/
SPOOL OFF